/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EifaSoftToken__factory } from "./EifaSoftToken__factory";
export { IBEP20__factory } from "./IBEP20__factory";
export { Ownable__factory } from "./Ownable__factory";
